opiproject/opi-api

README.md
doc/minutes/OPI API Minutes-40722.md

Meeting Minutes from 4/7/22 and Readme updates

---

doc/minutes/OPI API Minutes-33122.md
doc/minutes/OPI API Minutes-40722.md
doc/minutes/OPI API Minutes-42122.md
doc/minutes/OPI API Minutes-42822.md

Meeting Minutes for 4/21 and 4/28 plus format fixes

---

doc/minutes/OPI API Minutes-051222.md
doc/minutes/OPI API Minutes-50522.md

Meeting Minutes 5/12/22 and date correction on 5/5/22 minutes

---

doc/minutes/OPI API Minutes-60222.md

Meeting Minutes 6/2/22

---

doc/minutes/OPI API Minutes-60922.md

Meeting Minutes 6/9/22

---

USECASES.md
doc/minutes/OPI API Minutes-61622.md

Meeting Minutes 6/16

---

storage/README.md
storage/spec.md

storage: deep dive into spec

---

aiml/README.md
network/README.md

docs: add readme files

---

security/README.md
storage/spec.md

small changes, questions and readme

small changes, questions and readme

---

storage/spec.md

storage: add comments from last week

---

USECASES.md
aiml/README.md
doc/dpu-ovs/marvell-octeon/dpu_ovs_readme.md
network/README.md
security/README.md
storage/spec.md

lint: fix MD violations

---

storage/README.md
storage/spec.md

storage: add a picture

---

storage/spec.md

This is an outline for the SPEC versions as we moove forward

storage: add revisions to SPEC

---

doc/ipu_sdk_opi_api.md

Signed-off-by: Dan Daly <dan.daly@intel.com>

Comparison of Current OPI APIs to the top edge on the IPU SDK

---

.github/workflows/storage-skip.yml
.github/workflows/storage.yml
README.md
storage/Makefile

This adds simple CI to validate the storage protobuf files on pull
requests and merges to master.
Signed-off-by: Kyle Mestery <mestery@mestery.com>

CI: Add golang proto generation

---

.github/workflows/markdown.yml
storage/Makefile
storage/proto/autogen.md
storage/spec.md

storage: auto-generate proto to md

---

security/README.md

Signed-off-by: Kyle Mestery <mestery@mestery.com>

Fix broken link

---

doc/ipu_sdk_opi_api.md

Signed-off-by: Dan Daly <dan.daly@intel.com>

Added two more issues from today's OPI API discussion.

---

storage/proto/frontend.proto

storage: add Virtio-blk to proto

---

USECASES.md

Signed-off-by: msanders <marksanders194@gmail.com>

Update to UseCases

---

README.md

Update API Subgroup Focus description

---

doc/minutes/OPI API Minutes-August-22.md

August 11 notes and minutes

---

doc/minutes/OPI API Minutes-August-22.md

August 18 Meeting Minutes

---

README.md

Expand Readme with clarifications

---

network/Makefile
security/Makefile
storage/Makefile

proto: clean old files before generating new ones

---

.github/workflows/api-lint.yml

Action does not fail build, it just outputs results
Signed-off-by: patrick-alessi <patrick.alessi@dell.com>

Add aip linter action

---

.github/workflows/linters.yml
network/Makefile
security/Makefile
storage/Makefile

make: add api-linter

---

.github/workflows/linters.yml

ci: fix api linter

---

storage/proto/autogen.md
storage/proto/backend-null.proto

storage: add NULL to proto for debug

---

.github/workflows/linters.yml

ci: fix ignore md linter

---

.github/workflows/linters.yml
.github/workflows/network-skip.yml
.github/workflows/network.yml
.github/workflows/security-skip.yml
.github/workflows/security.yml
.github/workflows/storage-skip.yml
.github/workflows/storage.yml

ci: fix actions after folders restructure

---

common/Makefile
network/Makefile
security/Makefile
security/firewall/v1/autogen.md
storage/Makefile
storage/README.md
storage/v1/autogen.md

proto: add --rm and --user to makefiles

---

.github/workflows/linters.yml

Commit b33fa3b removed the firewall code, but this last reference was left dangling. This commit removes that.
Signed-off-by: Kyle Mestery <mestery@mestery.com>

firewall: Remove last trace

---

storage/v1/backend_aio.proto

Added AioControllerGetByName to allow retrieval of Aio Controller by name
Signed-off-by: PWAlessi <pwalessi1@gmail.com>

Added AioControllerGetByName to allow retrieval of Aio Controller by

---

.github/workflows/network.yml
.github/workflows/security.yml
.github/workflows/storage.yml

ci: fail if forget to auto-generate protos

---

storage/Makefile

[storage] [make] don;t copy files, map folders

---

doc/ipdk_storage_apis.md

Signed-off-by: Dan Daly <dan.daly@intel.com>

IPDK Storage APIs

---

doc/api-extensions.md

@sandersms @glimchb  - pls review
I have tried out some very basic things; as we try to extend we can update the documentation if there are more things to consider.
Signed-off-by: Vipin Jain <jainvipin@gmail.com>

document api extension methods

---

doc/api-extensions.md

Incorporate more feedback from leftovers on PR#224
Pls review @seroyer @glimchb @sandersms

follow up feedback from PR#224

---

.github/workflows/linters.yml

CI: add globbing to ignore

---

common/v1/autogen.md
common/v1/gen/go/inventory.pb.go
common/v1/gen/java/opi_api/inventory/v1/BIOSInfo.java
common/v1/gen/java/opi_api/inventory/v1/BIOSInfoOrBuilder.java
common/v1/gen/java/opi_api/inventory/v1/BaseboardInfo.java
common/v1/gen/java/opi_api/inventory/v1/BaseboardInfoOrBuilder.java
common/v1/gen/java/opi_api/inventory/v1/CPUInfo.java
common/v1/gen/java/opi_api/inventory/v1/CPUInfoOrBuilder.java
common/v1/gen/java/opi_api/inventory/v1/ChassisInfo.java
common/v1/gen/java/opi_api/inventory/v1/ChassisInfoOrBuilder.java
common/v1/gen/java/opi_api/inventory/v1/DeviceInfo.java
common/v1/gen/java/opi_api/inventory/v1/MemoryInfo.java
common/v1/gen/java/opi_api/inventory/v1/MemoryInfoOrBuilder.java
common/v1/gen/java/opi_api/inventory/v1/SystemInfo.java
common/v1/gen/java/opi_api/inventory/v1/SystemInfoOrBuilder.java
common/v1/inventory.proto
network/cloud/v1alpha1/autogen.md
network/k8s/v1alpha1/autogen.md
network/opinetcommon/v1alpha1/autogen.md
network/telco/v1alpha1/autogen.md
storage/v1alpha1/autogen.md

[inventory] Add documentation

---

doc/minutes/Minutes-Topics-Dec-2022.md
doc/minutes/Minutes-Topics-Jan-2023.md

Update Meeting Minutes

---

common/v1/inventory.proto
network/cloud/v1alpha1/autogen.md
network/k8s/v1alpha1/autogen.md
network/opinetcommon/v1alpha1/autogen.md
network/telco/v1alpha1/autogen.md
storage/v1alpha1/autogen.md

Add PCI device information

---

.github/renovate.json

ci: renovate fix regex

---

security/Makefile
security/v1/autogen.md

chore(security): prepare makefile to fix exceptions

---

.github/renovate.json
common/Makefile
network/cloud/Makefile
network/evpn-gw/Makefile
network/k8s/Makefile
network/opinetcommon/Makefile
network/telco/Makefile
security/Makefile
storage/Makefile
storage/README.md

ci: use fixed protoc-gen-doc docker image
